---
name: WebService-LibraryThing-ThingISBN
version: 0.502
author:
  - 'Anirvan Chatterjee <anirvan@cpan.org>'
abstract: Get ISBNs for all editions of a book
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Business::ISBN: 2
  Carp: 0
  Exporter: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
recommends:
  Time::HiRes: 0
configure_requires:
  Module::Build: 0.34
provides:
  WebService::LibraryThing::ThingISBN:
    file: lib/WebService/LibraryThing/ThingISBN.pm
    version: 0.502
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
